Add show delegate votes in consultations
CodiTramuntana/decidim-module-action_delegator pull request #1
Opened 2020-12-17 07:19 UTC by LauraJaimeC

Add a new feature in order to show delegates votes in consultations views.

The changes in view:
![Captura de pantalla de 2020-12-17 08-18-56](https://user-images.githubusercontent.com/75725233/102455823-8a75e980-4040-11eb-8bc3-20eca253893d.png)

2020-12-17 09:02 UTC, tramuntanal requested changes
Just one appreciation @LauraJaimeC

2020-12-17 09:02 UTC, tramuntanal commented on app/overrides/models/decidim/consultations/question.rb
> +    granters_ids = Decidim::ActionDelegator::Delegation.where(granter: authors).map(&:granter_id).uniq!
For performance, lets delegate all we can to the database, so better use something like
```suggestion
    granters_ids = Decidim::ActionDelegator::Delegation.select(:granter_id).where(granter: authors).group(:granter_id).pluck(:granter_id)
```

2020-12-17 09:04 UTC, tramuntanal commented
The project already has a test suite configured. Can we add some tests please? mainly to check the counters are correctly couting

2020-12-17 09:47 UTC, LauraJaimeC commented on app/overrides/models/decidim/consultations/question.rb
> +    granters_ids = Decidim::ActionDelegator::Delegation.where(granter: authors).map(&:granter_id).uniq!
Changes applied, thanks!

2020-12-17 16:29 UTC, sauloperez requested changes

2020-12-17 16:29 UTC, sauloperez commented on Gemfile.lock
> +    deface (1.5.3)
I'd like to question this addition. As per my experience in https://github.com/openfoodfoundation/openfoodnetwork/, I'm very reluctant to rely on Deface. It tends to lead to very hard and unmaintainable views. IMO, it's far better to simply duplicate the views and compare them when needed. Then, when upgrading the Decidim version we just need to spot the differences and adapt to them.

That being said, the `results.html.erb` is already copied in this repo so we don't need those Override instances. You can directly modify the view.

2020-12-17 16:29 UTC, sauloperez commented on app/overrides/models/decidim/consultations/question.rb
> +end
I'm afraid the various DB queries and ruby processing this requires, make this method highly inefficient. I'd rather create a query object that gets that count (chances are that you can reuse bits of existing query objects) straight in a single DB statement.

You can inner join the votes' authors with the consultation's delegation granters to get the count instead of having to fetch them all separately and loop through.

2020-12-17 16:31 UTC, sauloperez commented
@LauraJaimeC thanks a lot for this contribution! :heart_eyes: I'm glad to see this module is actually useful to someone else

2020-12-21 07:21 UTC, LauraJaimeC commented on Gemfile.lock
> +    deface (1.5.3)
Great!! I removed Deface and use the duplicated view.

2020-12-21 07:23 UTC, LauraJaimeC commented on app/overrides/models/decidim/consultations/question.rb
> +end
Thank you for your help! I changed this code, can you review again? thanks!! :+1:

2020-12-22 09:30 UTC, sauloperez requested changes

2020-12-22 09:30 UTC, sauloperez commented on app/overrides/models/decidim/consultations/question.rb
> +end
That's definitely better @LauraJaimeC ! however, IMO it'd be even better if we wrote this as a query object like https://github.com/CodiTramuntana/decidim-module-action_delegator/blob/master/app/queries/decidim/action_delegator/consultation_delegations.rb or any other in app/queries/action_delegator/. This way we don't need to override the `Decidim::Consultations::Question` which is always risky. We just need to pass in the votes' authors as an argument as this is all this query needs.

2020-12-22 09:30 UTC, sauloperez commented on app/overrides/models/decidim/consultation.rb
> +  end
So is this almost the same as app/overrides/models/decidim/consultations/question.rb but at consultation level? If so, I'd apply the same we do in the other total_delegates method and reuse as much as we can between them. Nothing stops us from passing in another ActiveRecord relation as argument as we did in https://github.com/CodiTramuntana/decidim-module-action_delegator/blob/master/app/queries/decidim/action_delegator/responses_by_membership.rb.

2020-12-28 09:38 UTC, LauraJaimeC commented on app/overrides/models/decidim/consultation.rb
> +  end
Changed! can you review again, please?

2020-12-28 09:38 UTC, LauraJaimeC commented on app/overrides/models/decidim/consultations/question.rb
> +end
Changed! can you review again, please?

2021-01-04 19:00 UTC, sauloperez commented on app/queries/decidim/action_delegator/delegates_votes_by_consultation.rb
> +      def total_delegates
we should stick to the convention of naming this `#query` as all the other query objects.

2021-01-04 19:00 UTC, sauloperez commented on app/queries/decidim/action_delegator/delegates_votes_by_consultation.rb
> +        @consultation.questions.each { |q| total_count += @relation.new(q).query }
This will perform as many SQL queries as questions in the consultation and then sum their counts in Ruby, which is much less efficient than getting the total straight from a single DB query. Also, the more questions the slower it gets.

We should instead manage to reuse `DelegatesVotesByQuestion` using ActiveRecord's [merge](https://apidock.com/rails/ActiveRecord/SpawnMethods/merge) to fetch the votes scoped by the consultation rather than the question. That may require you to slightly refactor `DelegatesVotesByQuestion` though. The trick is to combine ActiveRecord relations and pass them as arguments as required as you did here.

I personally find it easier to come up with the SQL statements I need first, and then convert them to ActiveRecord syntax. This way it's way harder to introduce N+1s by mistake.

2021-01-05 10:07 UTC, LauraJaimeC commented on app/queries/decidim/action_delegator/delegates_votes_by_consultation.rb
> +        @consultation.questions.each { |q| total_count += @relation.new(q).query }
Hi, I don't understand how to merge the two relations. :crying_cat_face:  The relation that gets the total votes per question does it only for one question, so how can I make that merge if I want all votes from all questions from a consultation? 

I got a relation that gets all the votes (delegates and non delegates) for a consultation, but I don't understand how to merge those two queries in order to gives me back the total delegated votes for a consultation.

2021-01-07 08:24 UTC, LauraJaimeC commented on app/queries/decidim/action_delegator/delegates_votes_by_consultation.rb
> +        @consultation.questions.each { |q| total_count += @relation.new(q).query }
Hello again, I refactored this part in other way, can you take a look? thanks!!

2021-01-07 11:04 UTC, sauloperez commented
Yes! that's almost what I meant. I took the chance to refactor it a bit further so we fully leverage AR's relations but I can't push to your fork so I left a patch in https://gist.github.com/sauloperez/8fbcedd7824ec39af7631fa061e16a7c which you can apply. Please, check it out and let me know. I think we can merge if you like it.

2021-01-07 11:45 UTC, LauraJaimeC commented
Thank you for the improvement!!!! I try to apply first patch in the branch but Git says the file is corrupted in line 142. 
Do you know why?

2021-01-07 12:25 UTC, sauloperez commented
Could you share the output?

2021-01-07 12:28 UTC, LauraJaimeC commented
➜ git apply ../../8fbcedd7824ec39af7631fa061e16a7c/improvement.patch 
error: parche corrupto en la línea 142

Only that.

2021-01-07 12:33 UTC, sauloperez commented
Try appending an empty line at the bottom of the file. That fixed it for me. That must have been my editor, which removes empty lines when saving.

2021-01-07 12:39 UTC, LauraJaimeC commented
Done!!!

2021-01-07 12:43 UTC, sauloperez approved these changes
:clap:

2021-01-07 12:45 UTC, sauloperez commented
I just noticed now this should point to coopdevs for me to merge it. It's currently pointing to CodiTramuntana's fork.

2021-01-07 12:48 UTC, LauraJaimeC commented
I can't change base :thinking: 

![Captura de pantalla de 2021-01-07 13-47-48](https://user-images.githubusercontent.com/75725233/103894282-fbb03600-50ee-11eb-8a8a-70236c18a675.png)

2021-01-07 14:20 UTC, sauloperez commented
You can close this one and open another PR

2021-01-07 14:25 UTC, closed without merging